default:
  golem_name: shinyAdmissions
  golem_version: 0.0.0.9007
  app_prod: no
production:
  app_prod: yes
testing:
  pins_server: "https://rs-connect.utahtech.edu"
  pins_account: "rsconnectapi!service"
  pins_key: !expr Sys.getenv("RSCONNECT_SERVICE_USER_API_KEY", "undefined")
dev:
  golem_wd: !expr here::here()
